Repository DeveloperAcademy-POSTECH/MacC-Team2-Nutty, pull requests merged in 2023-10, with the labels that each got.

#19 15 get address api
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/View/PostCodeInputView.swift
  Onbom/Onbom/View/PostCodeView.swift
  index.html
Labels: ✨ feature

#16 3 Add Camera
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/Camera/CameraManager.swift
  Onbom/Onbom/Core/Camera/CameraViewer.swift
  Onbom/Onbom/View/IDCard/CameraView.swift
  Onbom/Onbom/View/IDCard/ConfirmIDCardView.swift
  Onbom/Onbom/View/IDCard/PrepareIDCardView.swift
  Onbom/Onbom/View/IDCard/TakeIDCardView.swift
Labels: ✨ feature

#26 Modify Color
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Extensions/Color+Palette.swift
  Onbom/Onbom/Extensions/TextStyle+Extension.swift
Labels: 🚑 hotfix

#30 Create MainView / ApplyTypeView / MediHistoryView / PatientInfoView / RejectView / MediConditionView
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/form_history.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/form_history.imageset/form_history.svg
  Onbom/Onbom/Assets.xcassets/home.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/home.imageset/home.svg
  Onbom/Onbom/Assets.xcassets/notification.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/notification.imageset/notification.svg
  Onbom/Onbom/Assets.xcassets/profile.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/profile.imageset/profile.svg
  Onbom/Onbom/Assets.xcassets/security.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/security.imageset/security.svg
  Onbom/Onbom/Extensions/TextField+Extension.swift
  Onbom/Onbom/Extensions/UITabBarController+Extension.swift
  Onbom/Onbom/Extensions/View+Extension.swift
  Onbom/Onbom/Extensions/ViewModifier.swift
  Onbom/Onbom/Model/ValidationPreferenceKey.swift
  Onbom/Onbom/View/ApplyTypeView.swift
  Onbom/Onbom/View/Component/FormTextField.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/MediHistoryView.swift
  Onbom/Onbom/View/PatientInfoView.swift
  Onbom/Onbom/View/RejectView.swift
  Onbom/Onbom/View/TextFormView.swift
Labels: ✨ feature, 💄design

#34 Add inputfield components
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/IDCard.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/IDCard.imageset/IDCard.svg
  Onbom/Onbom/Assets.xcassets/Light.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Light.imageset/Light.svg
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Components/NavigationBarBackButton.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Components/PhoneNumberInputField.swift
  Onbom/Onbom/Extensions/TextStyle+Extension.swift
  Onbom/Onbom/View/IDCard/ConfirmIDCardView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/IDCard/IDCardOCRView.swift
  Onbom/Onbom/View/IDCard/PrepareIDCardView.swift
  Onbom/Onbom/View/IDCard/TakeIDCardView.swift
Labels: ✨ feature, 💄design

#21 Create Social Login
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Onbom/Onbom/Assets.xcassets/kakao_login_medium_wide.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/kakao_login_medium_wide.imageset/kakao_login_medium_wide.png
  Onbom/Onbom/Core/AuthenticationViewModel.swift
  Onbom/Onbom/Info.plist
  Onbom/Onbom/Onbom.entitlements
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/Resources/GoogleService-Info.plist
  Onbom/Onbom/View/LoginView.swift
Labels: ✨ feature

#46 28 create agentinfoview
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/View/AgentInfo/AgentInfoDetailView.swift
  Onbom/Onbom/View/AgentInfo/AgentInfoView.swift
Labels: 💄design

#45 31 create privacypolicyview
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/View/Form/PrivacyPolicyView.swift
  Onbom/Onbom/View/Form/TempWriteFormView.swift
Labels: ✨ feature, 💄design

#41 27 create signatureview
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/View/DigitalSignature/SignatureView.swift
Labels: ✨ feature, 💄design

#37 Create MediConditionView
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/MediConditionViewModel.swift
  Onbom/Onbom/Core/PatientInfoViewModel.swift
  Onbom/Onbom/Extensions/TextField+Extension.swift
  Onbom/Onbom/Extensions/TextStyle+Extension.swift
  Onbom/Onbom/Extensions/View+Extension.swift
  Onbom/Onbom/Extensions/ViewModifier.swift
  Onbom/Onbom/Model/ValidationPreferenceKey.swift
  Onbom/Onbom/View/ApplyTypeView.swift
  Onbom/Onbom/View/Component/FormTextField.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/MediConditionView.swift
  Onbom/Onbom/View/MediHistoryView.swift
  Onbom/Onbom/View/PatientInfoView.swift
  Onbom/Onbom/View/RejectView.swift
  Onbom/Onbom/View/TextFormView.swift
Labels: ✨ feature, 💄design

#44 Create StepView
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/View/ApplyTypeView.swift
  Onbom/Onbom/View/LoginView.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/MediHistoryView.swift
  Onbom/Onbom/View/PatientInfoView.swift
  Onbom/Onbom/View/RejectView.swift
  Onbom/Onbom/View/StepView.swift
Labels: 💄design

#43 Delete firebase-initialization-code
  Onbom/Onbom/OnbomApp.swift
Labels: 🚑 hotfix

#47 Create address view
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Extensions/TextStyle+Extension.swift
  Onbom/Onbom/Info.plist
  Onbom/Onbom/Model/ApplicationViewModel.swift
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/Resources/Font/Pretendard-Black.otf
  Onbom/Onbom/Resources/Font/Pretendard-Bold.otf
  Onbom/Onbom/Resources/Font/Pretendard-ExtraBold.otf
  Onbom/Onbom/Resources/Font/Pretendard-ExtraLight.otf
  Onbom/Onbom/Resources/Font/Pretendard-Light.otf
  Onbom/Onbom/Resources/Font/Pretendard-Medium.otf
  Onbom/Onbom/Resources/Font/Pretendard-Regular.otf
  Onbom/Onbom/Resources/Font/Pretendard-SemiBold.otf
  Onbom/Onbom/Resources/Font/Pretendard-Thin.otf
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/Address/PostCodeInputView.swift
  Onbom/Onbom/View/IDCard/ConfirmIDCardView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/PostCodeInputView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
Labels: ✨ feature, 💄design

#38 [Design/#29] Build CTAButton Design System
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/CTAButton.swift
  Onbom/Onbom/Components/RadioButton.swift
  Onbom/Onbom/Components/RadioButton2.swift
Labels: 💄design

#57 49 create addidcardtopdf function and agentinfodetailview
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/DigitalSignature/DigitalSignatureManager.swift
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/View/AgentInfo/AgentInfoDetailView.swift
  Onbom/Onbom/View/DigitalSignature/SignatureView.swift
  Onbom/Onbom/View/DigitalSignature/TempWriteSignatureView.swift
  Onbom/Onbom/View/Form/TempPDFView.swift
Labels: ✨ feature, 💄design

#53 Navigationstate management With Navigationstack
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/100.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/1024.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/114.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/120.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/144.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/152.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/167.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/172.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/180.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/196.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/20.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/216.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/29.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/40.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/48.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/50.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/55.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/57.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/58.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/60.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/66.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/72.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/76.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/80.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/87.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/88.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/92.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/Contents.json
  Onbom/Onbom/Components/NavigationBarBackButton.swift
  Onbom/Onbom/Core/HomeNavigationViewModel.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/Address/PostCodeInputView.swift
  Onbom/Onbom/View/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/ApplyTypeView.swift
  Onbom/Onbom/View/DigitalSignature/SignatureView.swift
  Onbom/Onbom/View/HomeView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/IDCard/IDCardOCRView.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/MediConditionView.swift
  Onbom/Onbom/View/MediHistoryView.swift
  Onbom/Onbom/View/PatientInfoView.swift
  Onbom/Onbom/View/RejectView.swift
  Onbom/Onbom/View/StepView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
Labels: ✨ feature

#32 Create camera ocr
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/Camera/CameraManager.swift
  Onbom/Onbom/Core/Camera/CameraViewer.swift
  Onbom/Onbom/Core/Camera/RectangleDetector.swift
  Onbom/Onbom/Core/Camera/TextRecognizer.swift
  Onbom/Onbom/Model/ApplicationViewModel.swift
  Onbom/Onbom/View/IDCard/CameraView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/IDCard/IDCardOCRView.swift
Labels: ✨ feature

#60 Modify userviewmodel
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Model/ApplicationViewModel.swift
  Onbom/Onbom/Model/File.swift
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/Address/PostCodeView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/IDCard/IDCardOCRView.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/PatientInfoView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
Labels: ✨ feature

#67 Add Image Asset
  Onbom/Onbom/Assets.xcassets/TestFlight/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/DescriptionView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/DescriptionView.imageset/DescriptionView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/DescriptionView.imageset/DescriptionView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/DescriptionView.imageset/DescriptionView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/IDCardDescriptionView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/IDCardDescriptionView.imageset/IDCardDescriptionView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/IDCardDescriptionView.imageset/IDCardDescriptionView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/IDCardDescriptionView.imageset/IDCardDescriptionView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView.imageset/MainView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView.imageset/MainView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView.imageset/MainView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Blue.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Blue.imageset/MainView_Blue.svg
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Brown.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Brown.imageset/MainView_Brown.svg
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Green.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Green.imageset/MainView_Green.svg
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Pink.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Pink.imageset/MainView_Pink.svg
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Purple.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Purple.imageset/MainView_Purple.svg
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Yellow.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MainView_Yellow.imageset/MainView_Yellow.svg
  Onbom/Onbom/Assets.xcassets/TestFlight/MediHistoryView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/MediHistoryView.imageset/MediHistoryView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/MediHistoryView.imageset/MediHistoryView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/MediHistoryView.imageset/MediHistoryView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/RejectView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/RejectView.imageset/RejectView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/RejectView.imageset/RejectView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/RejectView.imageset/RejectView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/StepView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/StepView.imageset/StepView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/StepView.imageset/StepView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/StepView.imageset/StepView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitLoadingView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitLoadingView.imageset/SubmitLoadingView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitLoadingView.imageset/SubmitLoadingView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitLoadingView.imageset/SubmitLoadingView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitView.imageset/SubmitView.png
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitView.imageset/SubmitView@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/SubmitView.imageset/SubmitView@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/warning.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/warning.imageset/warning.svg
Labels: 💄design

#68 Design modification
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmView.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
Labels: ✨ feature

#69 63 connect pdf function
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Model/ApplicationViewModel.swift
  Onbom/Onbom/View/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/DigitalSignature/SignatureView.swift
  Onbom/Onbom/View/DigitalSignature/TempWriteSignatureView.swift
  Onbom/Onbom/View/HomeView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/MediConditionView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
Labels: ✨ feature, 💄design

#71 65 modify screen details
  Onbom/Onbom/Assets.xcassets/MediHistoryImage.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/MediHistoryImage.imageset/MediHistoryImage.png
  Onbom/Onbom/Assets.xcassets/MediHistoryImage.imageset/MediHistoryImage@2x.png
  Onbom/Onbom/Assets.xcassets/MediHistoryImage.imageset/MediHistoryImage@3x.png
  Onbom/Onbom/Assets.xcassets/chevronLeft.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/chevronLeft.imageset/chevronLeft.png
  Onbom/Onbom/Assets.xcassets/chevronLeft.imageset/chevronLeft@2x.png
  Onbom/Onbom/Assets.xcassets/chevronLeft.imageset/chevronLeft@3x.png
  Onbom/Onbom/Components/Alert.swift
  Onbom/Onbom/Components/CTAButton.swift
  Onbom/Onbom/Components/NavigationBarBackButton.swift
  Onbom/Onbom/Components/RadioButton.swift
  Onbom/Onbom/Extensions/Color+Palette.swift
  Onbom/Onbom/Extensions/TextStyle+Extension.swift
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/View/ApplyTypeView.swift
  Onbom/Onbom/View/Form/PrivacyPolicyView.swift
  Onbom/Onbom/View/MediHistoryView.swift
Labels: 💄design

#78 Fix idcard recognizing bug
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/Model/ApplicationViewModel.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/IDCard/IDCardOCRView.swift
Labels: 🚑 hotfix

#82 80 fix homeview and modify signatureviewagentinfoview detail
  Onbom/Onbom/View/DigitalSignature/SignatureView.swift
  Onbom/Onbom/View/HomeView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
Labels: 💄design

#86 Modify design detail
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Extensions/View+Extension.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/IDCard/IDCardOCRView.swift
Labels: 💄design

#92 91 fix cameramanager bug
  Onbom/Onbom/Core/Camera/CameraManager.swift
Labels: 🚑 hotfix

#94 93 fix homeview modify view detail
  Onbom/Onbom/View/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/DigitalSignature/SignatureView.swift
  Onbom/Onbom/View/Form/PrivacyPolicyView.swift
  Onbom/Onbom/View/HomeView.swift
  Onbom/Onbom/View/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/MediHistoryView.swift
  Onbom/Onbom/View/SubmitCheckListView.swift
  Onbom/Onbom/View/SubmitView.swift
Labels: 💄design

#97 89 modify design detail
  Onbom/Onbom/View/ApplyTypeView.swift
  Onbom/Onbom/View/RejectView.swift
Labels: 💄design

#98 Design modification by junyoo
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/IDCard/IDCardDescriptionView.swift
Labels: 💄design

#100 Edit Details
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/CustomNavigationBar.swift
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/Components/NavigationBarBackButton.swift
  Onbom/Onbom/Core/HomeNavigationViewModel.swift
  Onbom/Onbom/Core/PatientInfoViewModel.swift
  Onbom/Onbom/View/Address/AddressFormView.swift
  Onbom/Onbom/View/Address/PostCodeView.swift
  Onbom/Onbom/View/HomeView.swift
  Onbom/Onbom/View/MainView.swift
  Onbom/Onbom/View/OnboardingView.swift
  Onbom/Onbom/View/PatientInfoView.swift
  Onbom/Onbom/View/StepView.swift
Labels: 🪡chore, 🐛bug

#102 Clean file and folder
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/CustomTabBarView.swift
  Onbom/Onbom/Components/FormTextField.swift
  Onbom/Onbom/Core/ViewModel/AuthenticationViewModel.swift
  Onbom/Onbom/Core/ViewModel/HomeNavigationViewModel.swift
  Onbom/Onbom/Core/ViewModel/MediConditionViewModel.swift
  Onbom/Onbom/Core/ViewModel/PatientInfoViewModel.swift
  Onbom/Onbom/Extensions/UITabBarController+Extension.swift
  Onbom/Onbom/Model/Address.swift
  Onbom/Onbom/Model/Agent.swift
  Onbom/Onbom/Model/ApplicationViewModel.swift
  Onbom/Onbom/Model/Patient.swift
  Onbom/Onbom/View/Address/PostCodeInputView.swift
  Onbom/Onbom/View/Address/PostCodeViewer.swift
  Onbom/Onbom/View/ContentView.swift
  Onbom/Onbom/View/DigitalSignature/TempWriteSignatureView.swift
  Onbom/Onbom/View/Form/TempPDFView.swift
  Onbom/Onbom/View/Form/TempWriteFormView.swift
  Onbom/Onbom/View/PrivacyPolicyView.swift
  Onbom/Onbom/View/SignatureView.swift
Labels: 🪡chore

#106 105 create calltaxiview
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/LaunchColor.colorset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/CallTaxi.imageset/CallTaxi.png
  Onbom/Onbom/Assets.xcassets/TestFlight/CallTaxi.imageset/CallTaxi@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/CallTaxi.imageset/CallTaxi@3x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/CallTaxi.imageset/Contents.json
  Onbom/Onbom/Components/Alert.swift
  Onbom/Onbom/Components/CTAButton.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/CustomTabBarView.swift
  Onbom/Onbom/Components/FormTextField.swift
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Components/RadioButton.swift
  Onbom/Onbom/Extensions/Color+Palette.swift
  Onbom/Onbom/Extensions/TextStyle+Extension.swift
  Onbom/Onbom/View/Donghaeng/CallTaxiView.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/Address/PostCodeInputView.swift
  Onbom/Onbom/View/LTCI/Address/PostCodeViewer.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoDetailView.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/LTCI/ApplyTypeView.swift
  Onbom/Onbom/View/LTCI/DescriptionView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardOCRView.swift
  Onbom/Onbom/View/LTCI/LoginView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/MediConditionView.swift
  Onbom/Onbom/View/LTCI/MediHistoryView.swift
  Onbom/Onbom/View/LTCI/OnboardingView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyView.swift
  Onbom/Onbom/View/LTCI/RejectView.swift
  Onbom/Onbom/View/LTCI/SignatureView.swift
  Onbom/Onbom/View/LTCI/StepView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: ✨ feature, 💄design
