Repository DeveloperAcademy-POSTECH/MacC-Team2-Nutty, pull requests merged in 2023-11, with the labels that each got.

#107 Edit Details
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Onbom/Onbom/Assets.xcassets/wrongInputField.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/wrongInputField.imageset/wrongInputField@1x.png
  Onbom/Onbom/Assets.xcassets/wrongInputField.imageset/wrongInputField@2x.png
  Onbom/Onbom/Assets.xcassets/wrongInputField.imageset/wrongInputField@3x.png
  Onbom/Onbom/Components/CTAButton.swift
  Onbom/Onbom/Components/CustomNavigationBar.swift
  Onbom/Onbom/Components/CustomTabBarView.swift
  Onbom/Onbom/Components/FormTextField.swift
  Onbom/Onbom/Core/Firebase/FirebaseStorageManager.swift
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Core/ViewModel/AuthenticationViewModel.swift
  Onbom/Onbom/Core/ViewModel/PatientInfoViewModel.swift
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/LoginView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
  Onbom/OnbomTests/PatientInfoViewModelTests.swift
Labels: 💄design, 🪡chore

#112 104 connect edit page in submitview and update detail
  Onbom/Onbom/Components/Alert.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/FormTextField.swift
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Components/RadioButton.swift
  Onbom/Onbom/Core/DigitalSignature/DigitalSignatureManager.swift
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Core/ViewModel/HomeNavigationViewModel.swift
  Onbom/Onbom/View/Donghaeng/CallTaxiView.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoDetailView.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/LTCI/ApplyTypeView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/LTCI/MediConditionView.swift
  Onbom/Onbom/View/LTCI/MediHistoryView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyView.swift
  Onbom/Onbom/View/LTCI/RejectView.swift
  Onbom/Onbom/View/LTCI/SignatureView.swift
  Onbom/Onbom/View/LTCI/StepView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: ✨ feature, 💄design

#113 Modify addressformview detail
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/Alert/Contents.json
  Onbom/Onbom/Assets.xcassets/Alert/check.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Alert/check.imageset/check.png
  Onbom/Onbom/Assets.xcassets/Alert/check.imageset/check@2x.png
  Onbom/Onbom/Assets.xcassets/Alert/check.imageset/check@3x.png
  Onbom/Onbom/Assets.xcassets/Alert/info.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Alert/info.imageset/info.png
  Onbom/Onbom/Assets.xcassets/Alert/info.imageset/info@2x.png
  Onbom/Onbom/Assets.xcassets/Alert/info.imageset/info@3x.png
  Onbom/Onbom/Assets.xcassets/Alert/security.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Alert/security.imageset/security.png
  Onbom/Onbom/Assets.xcassets/Alert/security.imageset/security@2x.png
  Onbom/Onbom/Assets.xcassets/Alert/security.imageset/security@3x.png
  Onbom/Onbom/Assets.xcassets/check.imageset/check.png
  Onbom/Onbom/Assets.xcassets/check.imageset/check@2x.png
  Onbom/Onbom/Assets.xcassets/check.imageset/check@3x.png
  Onbom/Onbom/Assets.xcassets/info.imageset/info.png
  Onbom/Onbom/Assets.xcassets/info.imageset/info@2x.png
  Onbom/Onbom/Assets.xcassets/info.imageset/info@3x.png
  Onbom/Onbom/Assets.xcassets/security.imageset/security.png
  Onbom/Onbom/Assets.xcassets/security.imageset/security@2x.png
  Onbom/Onbom/Assets.xcassets/security.imageset/security@3x.png
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Components/PhoneNumberInputField.swift
  Onbom/Onbom/Extensions/String+Validation.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
Labels: ✨ feature, 💄design

#110 Autocapture camera with drivers license
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Core/Camera/CameraManager.swift
  Onbom/Onbom/Core/Camera/Manager/CameraManager.swift
  Onbom/Onbom/Core/Camera/Manager/IDCardCameraManager.swift
  Onbom/Onbom/Core/Camera/OCR/DocumentTextRecognizer.swift
  Onbom/Onbom/Core/Camera/OCR/IDCardTextRecognizer.swift
  Onbom/Onbom/Core/Camera/OCR/TextRecognizable.swift
  Onbom/Onbom/Core/Camera/RectangleDetect/DocumentDetector.swift
  Onbom/Onbom/Core/Camera/RectangleDetect/IDCardDetector.swift
  Onbom/Onbom/Core/Camera/RectangleDetect/RectangleDetectable.swift
  Onbom/Onbom/Core/Camera/Viewer/DocumentCameraViewer.swift
  Onbom/Onbom/Core/Camera/Viewer/IDCardCameraViewer.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardOCRView.swift
Labels: ✨ feature

#120 Edit Details
  Onbom/Onbom/Components/RadioButton.swift
  Onbom/Onbom/Core/Firebase/FirebaseStorageManager.swift
  Onbom/Onbom/Core/ViewModel/HomeNavigationViewModel.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/LTCI/ApplyTypeView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/MediConditionView.swift
  Onbom/Onbom/View/LTCI/MediHistoryView.swift
  Onbom/Onbom/View/LTCI/OnboardingView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/StepView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: ✨ feature, 💄design

#126 Create ApplyHistoryView
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/ViewModel/HomeNavigationViewModel.swift
  Onbom/Onbom/Core/ViewModel/HomeViewModel.swift
  Onbom/Onbom/Model/Address.swift
  Onbom/Onbom/Model/Agent.swift
  Onbom/Onbom/Model/Patient.swift
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/ApplyHistoryView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/OnboardingView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: ✨ feature, 💄design

#123 Make Text Editable
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/NavigationBarBackButton.swift
  Onbom/Onbom/Core/ViewModel/HomeNavigationViewModel.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardOCRView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
Labels: ✨ feature

#130 [Hotfix] resolve conflict of SubmitCheckListView
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
Labels: 🚑 hotfix

#132 Edit IDCard-Address View design details
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardDescriptionView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardOCRView.swift
Labels: 💄design

#137 [Fix/#136] Fix SigatureView to StateObject
  Onbom/Onbom/View/LTCI/SignatureView.swift
Labels: 🚑 hotfix

#142 Hotfix by junyoo
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
Labels: 🚑 hotfix, 💄design

#141 133 make navigation
  Onbom/Onbom/Assets.xcassets/chevronRight.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/chevronRight.imageset/chevronRight.png
  Onbom/Onbom/Assets.xcassets/chevronRight.imageset/chevronRight@2x.png
  Onbom/Onbom/Assets.xcassets/chevronRight.imageset/chevronRight@3x.png
  Onbom/Onbom/Assets.xcassets/defaultCircle.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/defaultCircle.imageset/defaultCircle.png
  Onbom/Onbom/Assets.xcassets/defaultCircle.imageset/defaultCircle@2x.png
  Onbom/Onbom/Assets.xcassets/defaultCircle.imageset/defaultCircle@3x.png
  Onbom/Onbom/Assets.xcassets/selectedCircle.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/selectedCircle.imageset/selectedCircle.png
  Onbom/Onbom/Assets.xcassets/selectedCircle.imageset/selectedCircle@2x.png
  Onbom/Onbom/Assets.xcassets/selectedCircle.imageset/selectedCircle@3x.png
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
Labels: ✨ feature, 🪡chore

#144 [Fix] Edit Agent phone number field
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
Labels: 🚑 hotfix

#152 147 modify pdf signature size and add agentinfoview edit feature
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Model/Patient.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/ApplyTypeView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyDetailView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: 💄design, 🪡chore

#154 Modify validation
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/AddressInputField.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/Core/Camera/RectangleDetect/IDCardDetector.swift
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Model/Address.swift
  Onbom/Onbom/Model/Patient.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/ApplyTypeView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyDetailView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: 💄design, 🪡chore

#151 150 edit alert component
  Onbom/Onbom/Assets.xcassets/Alert/check.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Alert/info.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Alert/security.imageset/Contents.json
  Onbom/Onbom/Components/Alert.swift
  Onbom/Onbom/Components/CTAButton.swift
  Onbom/Onbom/Components/CityAddressInputField.swift
  Onbom/Onbom/Components/IDNumberInputField.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/SignatureView.swift
Labels: 💄design, 🪡chore

#157 [Fix] Resolve conflict
  Onbom/Onbom/Components/CTAButton.swift
  Onbom/Onbom/Components/NumberInputField.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
Labels: 🚑 hotfix

#165 161 modify pdfmanager privacypolicyview and update design detail
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/LaunchColor.colorset/Contents.json
  Onbom/Onbom/Assets.xcassets/LaunchLogo.imageset/LaunchScreenLogo.png
  Onbom/Onbom/Assets.xcassets/LaunchLogo.imageset/LaunchScreenLogo@2x.png
  Onbom/Onbom/Assets.xcassets/LaunchLogo.imageset/LaunchScreenLogo@3x.png
  Onbom/Onbom/Assets.xcassets/Logo.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Logo.imageset/Logo.png
  Onbom/Onbom/Assets.xcassets/Logo.imageset/Logo@2x.png
  Onbom/Onbom/Assets.xcassets/Logo.imageset/Logo@3x.png
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Info.plist
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyDetailView.swift
  Onbom/Onbom/View/LTCI/PrivacyPolicyView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitLoadingView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: ✨ feature, 💄design

#168 [Design] Create myInfoView
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/myInfoView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/myInfoView.imageset/myInfoView.png
  Onbom/Onbom/Assets.xcassets/myInfoView.imageset/myInfoView@2x.png
  Onbom/Onbom/Assets.xcassets/myInfoView.imageset/myInfoView@3x.png
  Onbom/Onbom/MyInfoView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
Labels: 💄design

#169 Modify agent model
  Onbom/Onbom/Core/Navigation/NavigationManager.swift
  Onbom/Onbom/Model/Address.swift
  Onbom/Onbom/Model/Agent.swift
  Onbom/Onbom/View/LTCI/Address/AddressFormView.swift
  Onbom/Onbom/View/LTCI/AgentInfo/AgentInfoView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
Labels: ✨ feature, 💄design

#173 Create mainview guide
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/AdBanner.swift
  Onbom/Onbom/Components/GuideView.swift
  Onbom/Onbom/Components/HomeNavigationBar.swift
  Onbom/Onbom/Components/LTCICardBack.swift
  Onbom/Onbom/Components/LTCICardFront.swift
  Onbom/Onbom/Core/ViewModel/HomeViewModel.swift
  Onbom/Onbom/Core/ViewModel/MainViewModel.swift
  Onbom/Onbom/Extensions/View+Extension.swift
  Onbom/Onbom/MyInfoView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
  Onbom/Onbom/View/LTCI/OnboardingView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
  Onbom/Onbom/View/LTCI/SubmitView.swift
Labels: ✨ feature

#174 Add bool field into patient model
  Onbom/Onbom/Core/Navigation/NavigationManager.swift
  Onbom/Onbom/Model/Patient.swift
  Onbom/Onbom/OnbomApp.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
  Onbom/Onbom/View/LTCI/PatientInfoView.swift
  Onbom/Onbom/View/LTCI/SubmitCheckListView.swift
Labels: ✨ feature, 🪡chore

#176 [HotFix] fix padding
  Onbom/Onbom/Components/GuideView.swift
Labels: 🪡chore

#181 166 update applyhistoryview
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/100.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/1024.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/114.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/120.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/144.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/152.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/167.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/172.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/180.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/196.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/20.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/216.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/29.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/40.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/48.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/50.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/55.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/57.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/58.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/60.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/66.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/72.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/76.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/80.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/87.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/88.png
  Onbom/Onbom/Assets.xcassets/AppIcon.appiconset/92.png
  Onbom/Onbom/Assets.xcassets/Important.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/Important.imageset/warning.png
  Onbom/Onbom/Assets.xcassets/Important.imageset/warning@2x.png
  Onbom/Onbom/Assets.xcassets/Important.imageset/warning@3x.png
  Onbom/Onbom/Core/PDF/PDFViewer.swift
  Onbom/Onbom/View/LTCI/ApplyHistoryView.swift
  Onbom/Onbom/View/LTCI/HomeView.swift
Labels: ✨ feature, 💄design

#186 Create descriptionview
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Assets.xcassets/DescriptionView.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/DescriptionView.imageset/DescriptionView.jpg
  Onbom/Onbom/Assets.xcassets/DescriptionView.imageset/DescriptionView@2x.jpg
  Onbom/Onbom/Assets.xcassets/DescriptionView.imageset/DescriptionView@3x.jpg
  Onbom/Onbom/Assets.xcassets/TestFlight/warning-rounded.imageset/Contents.json
  Onbom/Onbom/Assets.xcassets/TestFlight/warning-rounded.imageset/warning-rounded.png
  Onbom/Onbom/Assets.xcassets/TestFlight/warning-rounded.imageset/warning-rounded@2x.png
  Onbom/Onbom/Assets.xcassets/TestFlight/warning-rounded.imageset/warning-rounded@3x.png
  Onbom/Onbom/Components/ToastAlert.swift
  Onbom/Onbom/Extensions/View+Extension.swift
  Onbom/Onbom/Extensions/ViewModifier.swift
  Onbom/Onbom/MyInfoView.swift
  Onbom/Onbom/View/LTCI/DescriptionView.swift
  Onbom/Onbom/View/LTCI/IDCard/IDCardConfirmEditView.swift
  Onbom/Onbom/View/LTCI/MainView.swift
Labels: ✨ feature, 🐛bug

#188 185 refactoring pdfviewer applyhistoryview and connent detailrelation to pdf
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/LTCICardBack.swift
  Onbom/Onbom/Core/PDF/PDFManager.swift
  Onbom/Onbom/Core/PDF/PDFViewer.swift
  Onbom/Onbom/Model/Agent.swift
  Onbom/Onbom/View/LTCI/ApplyHistoryView.swift
Labels: ✨ feature, 💄design
