Repository DeveloperAcademy-POSTECH/MacC-Team2-Nutty, pull requests merged in 2023-09, with the labels that each got.

#7 [Fix] clear file reference
  Onbom/Onbom.xcodeproj/project.pbxproj
Labels: 🐛bug

#11 #9 feat add pdf feature
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Core/File.swift
  Onbom/Onbom/Core/PDFManager.swift
  Onbom/Onbom/Core/PDFViewer.swift
  Onbom/Onbom/Resources/File.swift
  Onbom/Onbom/Resources/LTCIForm.pdf
  Onbom/Onbom/View/ContentView.swift
  Onbom/Onbom/View/File.swift
Labels: ✨ feature

#14 12 add color extension and create inputfield component
  Onbom/Onbom.xcodeproj/project.pbxproj
  Onbom/Onbom/Components/InputField.swift
  Onbom/Onbom/Extensions/Color+Palette.swift
  Onbom/Onbom/Extensions/File.swift
Labels: ✨ feature, 💄design
